# Generated by Django 5.2.17 on 2026-08-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_user_aadhaar_number_user_designation_user_district_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="aadhaar_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="user",
            name="district",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="village",
        ),
    ]
