# Generated by Django 5.2.17 on 2026-08-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_farmerprofile_staffprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmerprofile",
            name="aadhaar_number",
        ),
    ]
