# Generated by Django 5.2.17 on 2026-08-30 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_farmerprofile_aadhaar_number"),
        ("procurement", "0008_alter_procurementcentre_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_profiles",
                to="procurement.state",
            ),
        ),
    ]
