# Generated by Django 5.2.17 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0003_procurementrequest_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="procurementcentre",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
