# Generated by Django 5.2.17 on 2026-08-30 10:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0004_procurementcentre_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("lgd_code", models.PositiveIntegerField(db_index=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["state__name", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="procurementcentre",
            options={"ordering": ["state__name", "district__name", "name"]},
        ),
        migrations.RemoveField(
            model_name="procurementrequest",
            name="district",
        ),
        migrations.RemoveField(
            model_name="procurementrequest",
            name="state",
        ),
        migrations.AddField(
            model_name="procurementcentre",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="procurementcentre",
            name="agency",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="procurementcentre",
            name="crop",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="procurementcentre",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="procurementcentre",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="procurementcentre",
            name="pincode",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="procurementcentre",
            name="season",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="procurementcentre",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="procurementrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="procurementcentre",
            name="code",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="procurementcentre",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="procurementcentre",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procurement_centres",
                to="procurement.district",
            ),
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("lgd_code", models.PositiveIntegerField(db_index=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="procurement_name_edcd75_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="district",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="districts",
                to="procurement.state",
            ),
        ),
        migrations.AlterField(
            model_name="procurementcentre",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procurement_centres",
                to="procurement.state",
            ),
        ),
        migrations.CreateModel(
            name="SubDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("lgd_code", models.PositiveIntegerField(db_index=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subdistricts",
                        to="procurement.district",
                    ),
                ),
            ],
            options={
                "ordering": ["district__state__name", "district__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("lgd_code", models.PositiveIntegerField(db_index=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subdistrict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="villages",
                        to="procurement.subdistrict",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "subdistrict__district__state__name",
                    "subdistrict__district__name",
                    "subdistrict__name",
                    "name",
                ],
            },
        ),
        migrations.AlterField(
            model_name="procurementcentre",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procurement_centres",
                to="procurement.village",
            ),
        ),
        migrations.AlterField(
            model_name="procurementrequest",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procurement_requests",
                to="procurement.village",
            ),
        ),
        migrations.AddIndex(
            model_name="procurementcentre",
            index=models.Index(fields=["code"], name="procurement_code_e0a38a_idx"),
        ),
        migrations.AddIndex(
            model_name="procurementcentre",
            index=models.Index(
                fields=["agency", "name"], name="procurement_agency_d8b49e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procurementrequest",
            index=models.Index(
                fields=["status", "preferred_date"],
                name="procurement_status_75a437_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(
                fields=["state", "name"], name="procurement_state_i_161ebb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(
                fields=("state", "name"), name="unique_district_name_per_state"
            ),
        ),
        migrations.AddIndex(
            model_name="subdistrict",
            index=models.Index(
                fields=["district", "name"], name="procurement_distric_c8b189_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subdistrict",
            constraint=models.UniqueConstraint(
                fields=("district", "name"), name="unique_subdistrict_name_per_district"
            ),
        ),
        migrations.AddIndex(
            model_name="village",
            index=models.Index(
                fields=["subdistrict", "name"], name="procurement_subdist_baa465_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="village",
            constraint=models.UniqueConstraint(
                fields=("subdistrict", "name"),
                name="unique_village_name_per_subdistrict",
            ),
        ),
    ]
