# Generated by Django 5.2.17 on 2026-08-30 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0005_district_alter_procurementcentre_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="procurementcentre",
            name="slots_per_day",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="If set, maximum tickets per day for this centre. Null = unlimited",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="procurementrequest",
            name="ticket_number",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="procurementrequest",
            constraint=models.UniqueConstraint(
                fields=("centre", "preferred_date", "ticket_number"),
                name="unique_centre_date_ticket",
            ),
        ),
    ]
