# Generated by Django 5.2.17 on 2026-08-30 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0007_remove_procurementcentre_district"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="procurementcentre",
            options={"ordering": ["state__name", "name"]},
        ),
        migrations.AlterField(
            model_name="procurementcentre",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procurement_centres",
                to="procurement.state",
            ),
        ),
        migrations.AddIndex(
            model_name="procurementcentre",
            index=models.Index(
                fields=["state", "name"], name="procurement_state_i_f55b59_idx"
            ),
        ),
    ]
