# Generated by Django 5.2.17 on 2026-08-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0008_alter_procurementcentre_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="procurementcentre",
            options={"ordering": ["state__name", "district__name", "name"]},
        ),
        migrations.RemoveField(
            model_name="procurementcentre",
            name="village",
        ),
        migrations.RemoveField(
            model_name="procurementrequest",
            name="village",
        ),
        migrations.AddField(
            model_name="procurementcentre",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procurement_centres",
                to="procurement.district",
            ),
        ),
        migrations.AddField(
            model_name="procurementrequest",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procurement_requests",
                to="procurement.district",
            ),
        ),
        migrations.AddIndex(
            model_name="procurementcentre",
            index=models.Index(
                fields=["state", "district", "name"],
                name="procurement_state_i_285464_idx",
            ),
        ),
    ]
